#!/bin/bash

set -euo pipefail

readonly GIT_REPO_URL="${GIT_REPO_URL-https://github.com/gregfolker/dotfiles}"
readonly GIT_BRANCH="${GIT_BRANCH-main}"

function usage() {
    cat <<EOF
Usage: ./bootstrap.sh [OPTIONS]

Install dependencies and clone dotfiles on a MacOS or Linux system. This
will install Homebrew automatically on MacOS if it is not already installed
and the user has sudo permissions. Can be downloaded and executed with the
convenient one liner:

    bash <(curl -fsSL https://raw.githubusercontent.com/gregfolker/dotfiles/main/bootstrap.sh)

Always inspect and verify the contents of downloaded scripts before executing them!

This will clone the dotfiles to ~/.dotfiles and initialize all symlinks.
EOF
}

function update_xcode() {
    if [ ! -f "/Library/Developer/CommandLineTools/usr/bin/git" ]; then
        echo "Xcode Command Line Tools is up to date, skipping..."
        return 0
    fi

    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    softwareupdate -i -a
    rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
}

function install_homebrew() {
    if command -v brew >/dev/null; then
        echo "Found $(brew --version), skipping..."
        return 0
    fi

    HOMEBREW_PREFIX="${HOMEBREW_PREFIX-/opt/homebrew}"
    if [ ! -d "$HOMEBREW_PREFIX" ]; then
        if ! sudo --validate 2>/dev/null; then
            echo "WARNING: $USER does not have permissions to install Homebrew, skipping..."
            return 0
        fi
        update_xcode
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
}

function download_dotfiles() {
    if [ -d ~/.dotfiles ]; then
        echo "dotfiles already found at ~/.dotfiles, skipping..."
        return 0
    fi

    if command -v git >/dev/null; then
        git clone --recursive "$GIT_REPO_URL" -b "$GIT_BRANCH" ~/.dotfiles
    else
        mkdir -vp ~/.dotfiles
        curl -L "$GIT_REPO_URL/archive/$GIT_BRANCH.tar.gz" -o /tmp/dotfiles.tar.gz
        tar -zxf /tmp/dotfiles.tar.gz --directory ~/.dotfiles --strip-components=1
        rm /tmp/dotfiles.tar.gz
    fi
}

function main() {
    echo "Bootstrapping dotfiles..."

    if [ "$(uname -s)" == "Darwin" ]; then
        install_homebrew
    fi

    download_dotfiles

    # https://mise.jdx.dev/installing-mise.html
    curl https://mise.run | sh
    export PATH="$HOME/.local/bin:$PATH"

    XDG_CONFIG_HOME="${XDG_CONFIG_HOME-$HOME/.config}"
    mkdir -vp "$XDG_CONFIG_HOME/mise"
    shopt -s dotglob nullglob
    for file in ~/.dotfiles/mise/*; do
        ln -svfF "$file" "$XDG_CONFIG_HOME/mise/$(basename "$file")"
    done
    shopt -u dotglob nullglob

    trap "popd >/dev/null" EXIT
    pushd "$XDG_CONFIG_HOME/mise" >/dev/null

    GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME-}"
    if [ -z "$GIT_AUTHOR_NAME" ]; then
        read -rp "Enter your name for git commits: " GIT_AUTHOR_NAME
    fi

    GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL-}"
    if [ -z "$GIT_AUTHOR_EMAIL" ]; then
        read -rp "Enter your email for git commits: " GIT_AUTHOR_EMAIL
    fi
    export GIT_AUTHOR_NAME
    export GIT_AUTHOR_EMAIL

    if [ "$(uname -s)" == "Darwin" ]; then
        # ~/.config/colima/ssh_config is generated by colima at
        # runtime so a placeholder needs to be present for
        # the symlink to be created.
        mkdir -vp "$XDG_CONFIG_HOME/colima"
        touch "$XDG_CONFIG_HOME/colima/ssh_config"
    fi

    # mise takes over from here.
    mise bootstrap --force-dotfiles --yes

    # install neovim plugins
    mise x -- nvim --headless "+Lazy! sync" +qa

    echo "Bootstrap complete. Re-load your environment for changes to take effect."
}

main "$@"
