brew "bat"
brew "colima"
brew "docker"
brew "fd"
brew "fzf"
brew "git-delta"
brew "go"
brew "jq"
brew "mosh"
brew "neovim"
brew "luarocks"
brew "tree-sitter-cli"
brew "pipx"
brew "pyenv"
brew "ripgrep"
brew "the_silver_searcher"
brew "tree"
brew "mise"
brew "tmux"
brew "tpack"

cask "ghostty"
cask "font-jetbrains-mono"

instance_eval(File.read("Brewfile.zephyr"))
