---
name: Validate
on: [push]  # yamllint disable-line rule:truthy
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Install stylua
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # This disables running `stylua`
          args: false
      - name: Run linters
        run: |
          make lint
        shell: bash
      - name: Run tests
        run: |
          make test
        shell: bash
